version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: dvdrental-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dvdrental
    ports:
      - "54332:5432"
    volumes:
      - ./dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar
